Updated reqs.txt, Modified networkcmps,Sending JSON paths to devices
leondavi/NErlNet pull request #117
Opened 2022-05-23 15:30 UTC by dordor7

2022-05-23 16:41 UTC, leondavi requested changes

2022-05-23 16:41 UTC, leondavi commented on src_py/apiServer/apiServer.py
> +            address = 'http://{}:8484/updateJsonPath'.format(ip)
@dordor7  There is a better formating approach in python 
f'http://{ip}:8484/updateJsonPath'
Moreover why 8484 port number is not a parameter?

2022-05-23 16:41 UTC, leondavi commented on src_py/apiServer/globalVars.py
>  jsonPathLocation = '/home/{}/workspace/NErlNet/jsonPath'.format(username)
Use the new path location: "/usr/local/lib/nerlnet-lib/NErlNet" that should be the same across all platforms after using the script NerlnetInstall.sh 
https://github.com/leondavi/NErlNet/blob/master/NerlnetInstall.sh 

@dordor7 @kapelnik @evgenyan95

2022-05-23 16:41 UTC, leondavi commented on src_py/requirements.txt
> +python-apt==2.0.0+ubuntu0.20.4.5
I think this is a wrong requirements.txt 
Why do we need packages that relates with ubuntu? 
On raspberry or orange pi there is debian not ubuntu and this requirements.txt will fail 

Please generate requirement.txt only with modules that you've imported in apiServer 
and Jupyter-lab 
We need the minimal requirement for it to work.

2022-05-24 08:10 UTC, kapelnik approved these changes

2022-05-30 07:32 UTC, leondavi approved these changes

2022-06-01 12:41 UTC, closed without merging