Warning fix
leondavi/NErlNet pull request #228
Opened 2023-08-02 15:02 UTC by halfway258

- added epochs (rounds) in source
- removed warnings
- fix "flask port in use" crash
- fixed missing data in python training loss graph

2023-08-05 13:27 UTC, halfway258 commented
verified better convergence of branch

2023-08-08 09:50 UTC, leondavi approved these changes

2023-08-10 21:54 UTC, leondavi requested changes

2023-08-10 21:54 UTC, leondavi commented on src_erl/Communication_Layer/http_Nerlserver/src/source/parser.erl
> +  ListOfLinesOfData = dataStrToNumericData(lists:droplast(Lines)),
What is the meaning of this line? Please add a comment in code

2023-08-12 14:13 UTC, leondavi requested changes

2023-08-12 14:13 UTC, leondavi commented on src_py/apiServer/apiServer.py
> +                confMatList[worker][j] = confusion_matrix(workerNeuronRes[worker][globe.TRUE_LABLE_IND][j], workerNeuronRes[worker][globe.PRED_LABLE_IND][j], normalize='all')
Make the normalization as an option.
 user might want to select in some more balanced cases

2023-08-13 21:21 UTC, leondavi approved these changes

2023-08-13 21:21 UTC, leondavi commented
@halfway258 
You can merge it 🙂

2023-08-16 11:21 UTC, merged