New routers
leondavi/NErlNet pull request #244
Opened 2023-09-03 14:48 UTC by galhilu

Hi David,
The changes to be reviewed are mostly in routerGenServer and include the creation of the routing table (that also uses a newly written function in NerlTools) in the init function, and the addition of 2 new cast functions: uniCast and broadCast. 
changes in other files  (mainGenServer and clientGenServer) were for testing purposes.

2023-09-03 19:03 UTC, galhilu commented on src_erl/Communication_Layer/http_Nerlserver/src/Router/routerGenserver.erl
> +  EtsRef = ets:new(rouint_table, [set]),
routing typo

2023-09-03 19:31 UTC, galhilu commented on src_erl/Communication_Layer/http_Nerlserver/src/Router/routerGenserver.erl
> +      Path="uniCast",
atom to list

2023-09-03 19:38 UTC, galhilu commented on src_erl/Communication_Layer/http_Nerlserver/src/Router/routerGenserver.erl
> +      1->
define

2023-09-03 19:41 UTC, galhilu commented on src_erl/Communication_Layer/http_Nerlserver/src/Router/routerGenserver.erl
> +        [Client]=DestClientList,
no client in names

2023-09-07 21:46 UTC, leondavi requested changes

2023-09-07 21:46 UTC, leondavi commented on src_erl/Communication_Layer/http_Nerlserver/src/nerl_tools.erl
> +-export([make_rouint_table/4]).
Typo

2023-09-07 21:46 UTC, leondavi commented on src_erl/Communication_Layer/http_Nerlserver/src/nerl_tools.erl
> +make_rouint_table(Ets,[],_Origin,_NerlnetGraph)->Ets;
Typo

2023-09-07 21:48 UTC, leondavi commented
@galhilu found typo in function name
@GuyPerets106 please review and approve

please validate that synthetic and mnist experiments pass and number of messages is correct.

@galhilu thanks for your contribution!

2023-10-16 23:15 UTC, closed without merging

2023-10-16 23:16 UTC, leondavi commented
This PR changes moved to FullFlowCI New Routers