Nn tiles
leondavi/NErlNet pull request #381
Opened 2024-08-01 10:16 UTC by Orisadek

add nn tiles - stats tiles

2024-08-01 20:54 UTC, leondavi requested changes

2024-08-05 10:30 UTC, ohad123 requested changes
Please change it back to Stats object.
If you want to generate StatsTiles object please define new function that generate it.

2024-08-05 10:36 UTC, ohad123 requested changes

2024-08-05 10:36 UTC, ohad123 commented on src_py/apiServer/experiment_flow.py
> +    def generate_stats(self, experiment_phase = None) -> StatsTiles:
Please change it back to Stats object.
If you want to generate StatsTiles object please define new function that generate it.

2024-08-05 10:36 UTC, ohad123 commented on src_py/apiServer/experiment_flow.py
> +        return StatsTiles(experiment_phase)
Fix it here to

2024-08-05 20:58 UTC, merged